# Generated by Django 3.2.9 on 2021-11-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_price', models.IntegerField()),
                ('rest_available', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_order', models.CharField(max_length=80)),
                ('rest_placed', models.CharField(max_length=50)),
                ('dish_placed', models.CharField(max_length=30)),
                ('total_price', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=50)),
                ('rest_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
    ]
