# Generated by Django 3.2.9 on 2021-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
