# Generated by Django 3.2.9 on 2021-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_alter_dishmodel_rest_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
